# Root Dockerfile (Dockerfile.base)
FROM python:3.10.11

# Arguments that can be passed at build time
ARG USER_NAME
ARG USER_ID
# Check if the user ID exists and remove the user if it does
RUN id -u $USER_ID && userdel -r $(getent passwd $USER_ID | cut -d: -f1) || true
# Create a user with a specific UID and add to users group
RUN useradd -m -u $USER_ID -s /bin/bash $USER_NAME
# Set the created user as the default user

# set root user for some admin tasks
USER root

# Install Python dependencies
RUN python3.10 -m ensurepip && \
    python3.10 -m pip install --upgrade pip


    # Copy the requirements and install
COPY requirements.txt ./requirements.txt
RUN pip install -r requirements.txt

# Set the created user as the default user
USER $USER_NAME
WORKDIR /home/${USER_NAME}/app

# Keep the container running by using tail on a non-exiting file (hack to keep the container alive)
CMD ["tail", "-f", "/dev/null"]