# Use the official R base image
FROM r-base:latest

# Arguments that can be passed at build time
ARG USER_NAME
ARG USER_ID
# Check if the user ID exists and remove the user if it does
RUN id -u $USER_ID && userdel -r $(getent passwd $USER_ID | cut -d: -f1) || true
# Create a user with a specific UID and add to users group
RUN useradd -m -u $USER_ID -s /bin/bash $USER_NAME
# Set the created user as the default user
USER $USER_NAME

RUN mkdir /home/${USER_NAME}/sample_data
#RUN mkdir /home/${USER_NAME}/app

COPY sample_data/ /home/${USER_NAME}/sample_data/


WORKDIR /home/${USER_NAME}/app

# Install R packages
# RUN R -e "install.packages('data.table', dependencies=TRUE, repos='https://cran.rstudio.com/')"
# RUN R -e "install.packages('recipes', dependencies=TRUE, repos='https://cran.rstudio.com/')"

# Keep the container running by using tail on a non-exiting file (hack to keep the container alive)
CMD ["tail", "-f", "/dev/null"]